### ISSUE TITLE
Hyperbot icon is not showing on thehyperdragon.github.io

### ISSUE THREAD

**Issue by TheHyperDragon** [TheHyperDragon/TheHyperDragon.github.io#1]
the bot pfp is not showing on the homepage of the site. It doesn't seem to be anywhere in the repo.

**Comment by TheHyperDragon** [comment]
I think I found the issue. I'm at school, and they block any traffic from discord here. I'll upload the bot pfp to the repo when I get home so it can be added. I don't change the bot pfp on a regular basis, so it's fine if the image on the site doesn't change with the image of the bot.

**Comment by cluzier** [comment]
I linked it to the discord official website so whenever you change the server icon, it changes on the site too. Much easier and automated process.
